# Generated by Django 4.2.4 on 2023-08-31 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0002_doctor_created_date_doctor_registration_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/patient'),
        ),
    ]
