# Generated by Django 4.2.4 on 2023-08-31 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0005_department_doctor_alter_doctor_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hms.doctor'),
        ),
    ]
