# Generated by Django 4.2.4 on 2023-08-31 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0006_alter_department_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='doctor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
