# Generated by Django 4.2.4 on 2023-08-31 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0008_doctor_user_patient_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='registration_no',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='registration_no',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
