# Generated by Django 4.2.4 on 2023-08-31 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0010_alter_department_doctor_alter_doctor_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='doctor',
        ),
        migrations.CreateModel(
            name='Department_Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hms.department')),
                ('doctor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hms.doctor')),
            ],
        ),
    ]
