# Generated by Django 4.2.4 on 2023-08-31 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0011_remove_department_doctor_department_doctor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department_Doctor',
        ),
    ]
