# Generated by Django 4.2.4 on 2023-08-31 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0012_delete_department_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
