# Generated by Django 4.2.4 on 2023-08-31 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0013_patient_date_alter_patient_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='last_name',
        ),
    ]
