# Generated by Django 4.2.4 on 2023-08-31 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0014_rename_first_name_patient_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='registration_no',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='registration_no',
        ),
    ]
