# Generated by Django 4.2.4 on 2023-09-01 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0015_rename_first_name_doctor_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='date',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='time',
        ),
        migrations.AddField(
            model_name='patient',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
