# Generated by Django 4.2.4 on 2023-09-02 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0017_remove_patient_date_time_patient_date_patient_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='date',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='time',
        ),
        migrations.AddField(
            model_name='patient',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
