# Generated by Django 4.2.4 on 2023-09-02 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0019_alter_doctor_gender_alter_patient_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.CharField(choices=[('', 'Choose Gender'), ('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('', 'Choose Gender'), ('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=100),
        ),
    ]
