# Generated by Django 4.2.4 on 2023-09-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0022_patient_first_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='first_login',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
