# Generated by Django 4.2.4 on 2023-09-06 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0023_doctor_first_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment_DateTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='patient',
            name='date_time',
        ),
        migrations.AddField(
            model_name='patient',
            name='appointment_datetime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hms.appointment_datetime'),
        ),
    ]
