# Generated by Django 4.2.4 on 2023-09-06 06:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hms', '0026_remove_patient_department_remove_patient_doctor_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointment_DateTime',
            new_name='Appointment',
        ),
    ]
