# Generated by Django 4.2.4 on 2023-09-06 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0027_rename_appointment_datetime_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='appointment_datetime',
            new_name='appointment',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='user',
        ),
    ]
